k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:us-east-1:365784066259:cluster/eksprdtitan01
  currentCluster: arn:aws:eks:us-east-1:365784066259:cluster/eksprdtitan01
  clusters:
    arn:aws:eks:us-east-1:365784066259:cluster/eksprdtitan01:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - turn3
        - turn-cache-consumer
        - gitlab-runner
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-spawulski
